# -*- coding: utf-8 -*-
"""HW5Q13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zS3ScjVssDJzsPQ-ER6WSvEg3egADgXN
"""

!pip install ISLP

# === 0) 環境與資料 ===
import numpy as np
import pandas as pd

# ISLP：Python 版 ISL 的資料與工具
# pip install ISLP statsmodels scikit-learn
from ISLP import load_data

import matplotlib.pyplot as plt
import statsmodels.formula.api as smf

from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis, QuadraticDiscriminantAnalysis
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import StandardScaler, PolynomialFeatures
from sklearn.pipeline import make_pipeline

# 載入 Weekly 資料
Weekly = load_data('Weekly')  # 欄位包含: Year, Today, Direction(Up/Down), Lag1..Lag5, Volume
Weekly.head()

# 數值摘要
print(Weekly.describe(include='all'))

# 類別分佈（Direction）
print('\nDirection counts:\n', Weekly['Direction'].value_counts())

# 相關係數（只看數值欄位）
print('\nCorrelation matrix (numeric columns):\n', Weekly.select_dtypes(np.number).corr())

# 圖形摘要（幾個最有用的）
fig, axes = plt.subplots(1, 3, figsize=(15,4))
Weekly.groupby('Year')['Volume'].mean().plot(ax=axes[0], title='Avg Volume by Year')
axes[0].set_xlabel('Year'); axes[0].set_ylabel('Avg Volume')

axes[1].scatter(Weekly['Lag2'], Weekly['Today'], s=10)
axes[1].set_title('Today vs Lag2'); axes[1].set_xlabel('Lag2'); axes[1].set_ylabel('Today')

Weekly['Today'].hist(bins=30, ax=axes[2])
axes[2].set_title('Histogram of Today'); axes[2].set_xlabel('Today return'); axes[2].set_ylabel('count')
plt.tight_layout(); plt.show()

Weekly['Direction_bin'] = (Weekly['Direction'] == 'Up').astype(int)

logit_full = smf.logit("Direction_bin ~ Lag1 + Lag2 + Lag3 + Lag4 + Lag5 + Volume", data=Weekly).fit()
print(logit_full.summary())

proba_full = logit_full.predict(Weekly)
pred_full = (proba_full >= 0.5).astype(int)

cm_full = confusion_matrix(Weekly['Direction_bin'], pred_full)
acc_full = accuracy_score(Weekly['Direction_bin'], pred_full)

print("Confusion Matrix (Full):\n", cm_full)
print("Accuracy (Full):", acc_full)
print(classification_report(Weekly['Direction_bin'], pred_full, target_names=['Down','Up']))

train = Weekly['Year'] <= 2008
test  = Weekly['Year'] >= 2009

logit_lag2 = smf.logit("Direction_bin ~ Lag2", data=Weekly[train]).fit()
print(logit_lag2.summary())

proba_te = logit_lag2.predict(Weekly[test])
pred_te = (proba_te >= 0.5).astype(int)
cm_logit = confusion_matrix(Weekly.loc[test, 'Direction_bin'], pred_te)
acc_logit = accuracy_score(Weekly.loc[test, 'Direction_bin'], pred_te)

print("Logit(Lag2) Test Confusion Matrix:\n", cm_logit)
print("Logit(Lag2) Test Accuracy:", acc_logit)