# -*- coding: utf-8 -*-
"""HW6Q15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14JDur-oS2LWaDZ9auw38V3_3NDlgf5tj
"""

# ===== ISLP Ch.2 — Q15: Writing functions =====
# (a) Power(): 印出 2**3
def Power():
    print(2 ** 3)

# 測試
Power()  # 8


# (b) Power2(x, a): 印出 x**a
def Power2(x, a):
    print(x ** a)

# 測試
Power2(3, 8)  # 6561


# (c) 用 Power2() 計算 10**3、8**17、13**13
Power2(10, 3)   # 1000
Power2(8, 17)   # 2251799813685248
Power2(13, 13)  # 302875106592253


# (d) Power3(x, a): 回傳 x**a（不用印出，改成 return）
def Power3(x, a):
    result = x ** a
    return result

# 測試
val = Power3(2, 10)
print("Power3(2,10) =", val)  # 1024


# (e) 使用 Power3() 繪製 f(x) = x^2，x=1..10
import numpy as np
import matplotlib.pyplot as plt

xs = np.arange(1, 11)           # 1,2,...,10
ys = np.array([Power3(x, 2) for x in xs])

fig, ax = plt.subplots()
ax.plot(xs, ys, marker='o')
ax.set_xlabel("x")
ax.set_ylabel("x^2")
ax.set_title("f(x) = x^2 for x = 1..10")

# 可選：如果想要對數刻度，取消下列註解
# ax.set_xscale('log')
# ax.set_yscale('log')

plt.show()


# (f) PlotPower(xs, a): 針對給定的 x 序列與固定的 a，畫出 x 對 x**a
def PlotPower(xs, a, logx=False, logy=False, title=None):
    """
    xs: 可迭代的 x 值（例如 np.arange(1, 11)）
    a : 指數
    logx/logy: 是否將 x 或 y 軸用對數尺度
    title: 自訂圖標題（預設自動產生）
    """
    xs = np.asarray(xs)
    ys = np.array([Power3(x, a) for x in xs])

    fig, ax = plt.subplots()
    ax.plot(xs, ys, marker='o')
    ax.set_xlabel("x")
    ax.set_ylabel(f"x^{a}")
    if title is None:
        title = f"f(x) = x^{a}"
    ax.set_title(title)

    if logx:
        ax.set_xscale('log')
    if logy:
        ax.set_yscale('log')

    plt.show()

# 示範：畫出 x=1..10 的立方
PlotPower(np.arange(1, 11), 3)