# -*- coding: utf-8 -*-
"""HW6Q13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qkcHjJegC-q6RvSm5w8mand2MlJbsGwu
"""

!pip install ISLP

# === 0) 環境與資料 ===
import numpy as np
import pandas as pd

# ISLP：Python 版 ISL 的資料與工具
# pip install ISLP statsmodels scikit-learn
from ISLP import load_data

import matplotlib.pyplot as plt
import statsmodels.formula.api as smf

from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis, QuadraticDiscriminantAnalysis
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import StandardScaler, PolynomialFeatures
from sklearn.pipeline import make_pipeline

# 載入 Weekly 資料
Weekly = load_data('Weekly')  # 欄位包含: Year, Today, Direction(Up/Down), Lag1..Lag5, Volume
Weekly.head()

# 數值摘要
print(Weekly.describe(include='all'))

# 類別分佈（Direction）
print('\nDirection counts:\n', Weekly['Direction'].value_counts())

# 相關係數（只看數值欄位）
print('\nCorrelation matrix (numeric columns):\n', Weekly.select_dtypes(np.number).corr())

# 圖形摘要（幾個最有用的）
fig, axes = plt.subplots(1, 3, figsize=(15,4))
Weekly.groupby('Year')['Volume'].mean().plot(ax=axes[0], title='Avg Volume by Year')
axes[0].set_xlabel('Year'); axes[0].set_ylabel('Avg Volume')

axes[1].scatter(Weekly['Lag2'], Weekly['Today'], s=10)
axes[1].set_title('Today vs Lag2'); axes[1].set_xlabel('Lag2'); axes[1].set_ylabel('Today')

Weekly['Today'].hist(bins=30, ax=axes[2])
axes[2].set_title('Histogram of Today'); axes[2].set_xlabel('Today return'); axes[2].set_ylabel('count')
plt.tight_layout(); plt.show()

Weekly['Direction_bin'] = (Weekly['Direction'] == 'Up').astype(int)

logit_full = smf.logit("Direction_bin ~ Lag1 + Lag2 + Lag3 + Lag4 + Lag5 + Volume", data=Weekly).fit()
print(logit_full.summary())

proba_full = logit_full.predict(Weekly)
pred_full = (proba_full >= 0.5).astype(int)

cm_full = confusion_matrix(Weekly['Direction_bin'], pred_full)
acc_full = accuracy_score(Weekly['Direction_bin'], pred_full)

print("Confusion Matrix (Full):\n", cm_full)
print("Accuracy (Full):", acc_full)
print(classification_report(Weekly['Direction_bin'], pred_full, target_names=['Down','Up']))

train = Weekly['Year'] <= 2008
test  = Weekly['Year'] >= 2009

logit_lag2 = smf.logit("Direction_bin ~ Lag2", data=Weekly[train]).fit()
print(logit_lag2.summary())

proba_te = logit_lag2.predict(Weekly[test])
pred_te = (proba_te >= 0.5).astype(int)
cm_logit = confusion_matrix(Weekly.loc[test, 'Direction_bin'], pred_te)
acc_logit = accuracy_score(Weekly.loc[test, 'Direction_bin'], pred_te)

print("Logit(Lag2) Test Confusion Matrix:\n", cm_logit)
print("Logit(Lag2) Test Accuracy:", acc_logit)

X_tr = Weekly.loc[train, ['Lag2']].values
y_tr = Weekly.loc[train, 'Direction_bin'].values
X_te = Weekly.loc[test,  ['Lag2']].values
y_te = Weekly.loc[test,  'Direction_bin'].values

lda = LinearDiscriminantAnalysis().fit(X_tr, y_tr)
pred_lda = lda.predict(X_te)
cm_lda = confusion_matrix(y_te, pred_lda)
acc_lda = accuracy_score(y_te, pred_lda)
print("LDA(Lag2) Test Confusion Matrix:\n", cm_lda)
print("LDA(Lag2) Test Accuracy:", acc_lda)

qda = QuadraticDiscriminantAnalysis().fit(X_tr, y_tr)
pred_qda = qda.predict(X_te)
cm_qda = confusion_matrix(y_te, pred_qda)
acc_qda = accuracy_score(y_te, pred_qda)
print("QDA(Lag2) Test Confusion Matrix:\n", cm_qda)
print("QDA(Lag2) Test Accuracy:", acc_qda)

knn1 = make_pipeline(StandardScaler(), KNeighborsClassifier(n_neighbors=1))
knn1.fit(X_tr, y_tr)
pred_knn1 = knn1.predict(X_te)
cm_knn1 = confusion_matrix(y_te, pred_knn1)
acc_knn1 = accuracy_score(y_te, pred_knn1)
print("KNN(k=1, Lag2) Test Confusion Matrix:\n", cm_knn1)
print("KNN(k=1, Lag2) Test Accuracy:", acc_knn1)

nb = GaussianNB().fit(X_tr, y_tr)
pred_nb = nb.predict(X_te)
cm_nb = confusion_matrix(y_te, pred_nb)
acc_nb = accuracy_score(y_te, pred_nb)
print("Naive Bayes(Lag2) Test Confusion Matrix:\n", cm_nb)
print("Naive Bayes(Lag2) Test Accuracy:", acc_nb)

results = {
    'Logit(Lag2)': acc_logit,
    'LDA(Lag2)': acc_lda,
    'QDA(Lag2)': acc_qda,
    'KNN(k=1, Lag2)': acc_knn1,
    'NaiveBayes(Lag2)': acc_nb
}
print("Test Accuracies (2009–2010):")
for k,v in results.items():
    print(f"{k:16s} : {v:.4f}")

best_model = max(results, key=results.get)
print("\nBest on held-out (2009–2010):", best_model, "acc =", results[best_model])

import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis, QuadraticDiscriminantAnalysis
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import StandardScaler, PolynomialFeatures
from sklearn.pipeline import make_pipeline
from sklearn.metrics import confusion_matrix, accuracy_score

# 切分訓練/測試集 (1990–2008) vs (2009–2010)
train = Weekly['Year'] <= 2008
test  = Weekly['Year'] >= 2009
y_tr  = Weekly.loc[train, 'Direction_bin'].values
y_te  = Weekly.loc[test, 'Direction_bin'].values

# 各種特徵組合
X1_tr = Weekly.loc[train, ['Lag2']].values
X1_te = Weekly.loc[test,  ['Lag2']].values

X2_tr = Weekly.loc[train, ['Lag2', 'Volume']].values
X2_te = Weekly.loc[test,  ['Lag2', 'Volume']].values

# 加入多項式特徵（Lag1, Lag2, Volume 二次項與交互作用）
poly = PolynomialFeatures(degree=2, include_bias=False)
X3_tr = poly.fit_transform(Weekly.loc[train, ['Lag1','Lag2','Volume']].values)
X3_te = poly.transform(Weekly.loc[test,  ['Lag1','Lag2','Volume']].values)

results = []

# Helper function
def record_result(name, y_true, y_pred):
    acc = accuracy_score(y_true, y_pred)
    cm = confusion_matrix(y_true, y_pred)
    results.append((name, acc, cm))

# Logistic Regression
log1 = make_pipeline(StandardScaler(), LogisticRegression(max_iter=1000))
log1.fit(X1_tr, y_tr)
record_result("Logit(Lag2)", y_te, log1.predict(X1_te))

log2 = make_pipeline(StandardScaler(), LogisticRegression(max_iter=1000))
log2.fit(X2_tr, y_tr)
record_result("Logit(Lag2+Vol)", y_te, log2.predict(X2_te))

log3 = make_pipeline(StandardScaler(), LogisticRegression(max_iter=1000))
log3.fit(X3_tr, y_tr)
record_result("Logit(Poly2 Lag1,Lag2,Vol)", y_te, log3.predict(X3_te))

# LDA
lda1 = LinearDiscriminantAnalysis().fit(X1_tr, y_tr)
record_result("LDA(Lag2)", y_te, lda1.predict(X1_te))

lda2 = LinearDiscriminantAnalysis().fit(X2_tr, y_tr)
record_result("LDA(Lag2+Vol)", y_te, lda2.predict(X2_te))

lda3 = LinearDiscriminantAnalysis().fit(X3_tr, y_tr)
record_result("LDA(Poly2 Lag1,Lag2,Vol)", y_te, lda3.predict(X3_te))

# QDA
qda1 = QuadraticDiscriminantAnalysis().fit(X1_tr, y_tr)
record_result("QDA(Lag2)", y_te, qda1.predict(X1_te))

qda2 = QuadraticDiscriminantAnalysis().fit(X2_tr, y_tr)
record_result("QDA(Lag2+Vol)", y_te, qda2.predict(X2_te))

qda3 = QuadraticDiscriminantAnalysis().fit(X3_tr, y_tr)
record_result("QDA(Poly2 Lag1,Lag2,Vol)", y_te, qda3.predict(X3_te))

# Naive Bayes
nb1 = GaussianNB().fit(X1_tr, y_tr)
record_result("NaiveBayes(Lag2)", y_te, nb1.predict(X1_te))

nb2 = GaussianNB().fit(X2_tr, y_tr)
record_result("NaiveBayes(Lag2+Vol)", y_te, nb2.predict(X2_te))

# KNN 掃 K 值
for k in [1,3,5,7,9,11,15,21,25,31]:
    knn = make_pipeline(StandardScaler(), KNeighborsClassifier(n_neighbors=k))
    knn.fit(X2_tr, y_tr)
    record_result(f"KNN(k={k}, Lag2+Vol)", y_te, knn.predict(X2_te))

# 彙整與輸出
df_res = pd.DataFrame(results, columns=['Model','Accuracy','ConfusionMatrix']).sort_values(by='Accuracy', ascending=False)
print(df_res[['Model','Accuracy']])
best = df_res.iloc[0]
print("\n=== Best Model on Held-out (2009–2010) ===")
print(best['Model'])
print("Accuracy:", best['Accuracy'])
print("Confusion Matrix:\n", best['ConfusionMatrix'])